version: '3'
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - '33060:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
  rest-api:
    build:
      context: .
      args:
        - JAR_FILE=target/*.jar
        - DB_PASSWORD=password
        - DB_SERVER=mysql-db
        - DB_PORT=3306
    container_name: 'umg-sesion12'
    ports:
      - '8080:8080'
    links:
      - mysql-db

volumes:
  mysql-db-data: